project:
  type: website
  output-dir: docs

website:
  title: "Saurav Singh"
  navbar:
    left:
      - text: About me
        href: about.qmd
      - text: Blog
        href: index.qmd
      - text: TIL
        href: TIL.qmd
      
    right:
      - icon: github
        href: https://github.com/saurav2040
      - icon: twitter
        href: https://x.com/saurav2023
      - archive.qmd
format:
  html:
    theme: minty
    css: styles.css



