project:
  type: website
  output-dir: docs

website:
  title: "Saurav Singh"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/saurav2040
      - icon: twitter
        href: https://twitter.com/saurav2023
      - archive.qmd
format:
  html:
    theme: cosmo
    css: styles.css



